name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheckname: Deploy kernel module

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: balenalib/raspberrypi3-debian:latest
      options: --privileged
    steps:
      - name: Clone kernel
        uses: actions/checkout@v2
        with:
          repository: torvalds/linux
          ref: v5.10.25

      - name: Install dependencies
        run: apt-get update && apt-get install -y make gcc

      - name: Compile module
        run: make -C /github/workspace -f /github/workspace/Makefile

      - name: Load module
        run: insmod /github/workspace/my_module.ko

      - name: Run tests
        run: /github/workspace/test.sh

      - name: Unload module
        run: rmmod my_module
